<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Loading-and-inspecting-data" data-toc-modified-id="Loading-and-inspecting-data-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Loading and inspecting data</a></span><ul class="toc-item"><li><span><a href="#merged_data" data-toc-modified-id="merged_data-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>merged_data</a></span></li><li><span><a href="#country_codes" data-toc-modified-id="country_codes-1.2"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>country_codes</a></span></li><li><span><a href="#loc_region_codes" data-toc-modified-id="loc_region_codes-1.3"><span class="toc-item-num">1.3&nbsp;&nbsp;</span>loc_region_codes</a></span></li><li><span><a href="#target_data" data-toc-modified-id="target_data-1.4"><span class="toc-item-num">1.4&nbsp;&nbsp;</span>target_data</a></span></li></ul></li><li><span><a href="#Matching-location-data" data-toc-modified-id="Matching-location-data-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Matching location data</a></span><ul class="toc-item"><li><span><a href="#Imputing-missing-values" data-toc-modified-id="Imputing-missing-values-2.1"><span class="toc-item-num">2.1&nbsp;&nbsp;</span>Imputing missing values</a></span></li><li><span><a href="#OHE-region" data-toc-modified-id="OHE-region-2.2"><span class="toc-item-num">2.2&nbsp;&nbsp;</span>OHE region</a></span></li><li><span><a href="#OHE-country" data-toc-modified-id="OHE-country-2.3"><span class="toc-item-num">2.3&nbsp;&nbsp;</span>OHE country</a></span></li><li><span><a href="#OHE-local-region" data-toc-modified-id="OHE-local-region-2.4"><span class="toc-item-num">2.4&nbsp;&nbsp;</span>OHE local region</a></span></li></ul></li><li><span><a href="#Merge-all-data-and-drop-columns" data-toc-modified-id="Merge-all-data-and-drop-columns-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Merge all data and drop columns</a></span></li></ul></div>

1 - Match regions to target file by country code <br>
2 - Match local regions to target file by region code<br>
3 - OHE country<br>
4 - OHE local region

In [1]:
%load_ext autoreload
%autoreload 2

# Loading and inspecting data

In [2]:
import pandas as pd
import numpy as np

In [3]:
file_path1='./sla-preprocessing-data/merged_data_26_feb.xlsx' # investor data
file_path2='./sla-preprocessing-data/countries_regions_codes.xlsx' # country codes table
file_path3='./sla-preprocessing-data/regions_202202261659.csv' # local regions table
file_path4='./sla-preprocessing-data/investor_deals.xlsx' # target data

## merged_data

In [4]:
merged_data=pd.read_excel(file_path1)
merged_data=merged_data.drop(['Unnamed: 0'],axis=1)

## country_codes

In [5]:
country_codes=pd.read_excel(file_path2)
country_codes=country_codes.drop(['Unnamed: 0'], axis=1)

## loc_region_codes

In [6]:
loc_region_codes=pd.read_csv(file_path3, encoding='utf-8', delimiter=';')
loc_region_codes=loc_region_codes.drop(['name_de','name_fr','name_es'],axis=1)
loc_region_codes.columns=['local_region_id', 'country_id', 'local_region_name']

## target_data

In [7]:
target_data=pd.read_excel(file_path4)

In [8]:
target_region=target_data[['deal_id', 'target_country_id', 'target_region_id']]

In [9]:
target_region['target_country_id'] = target_region['target_country_id'].fillna(0).astype(int)
target_region['target_region_id'] = target_region['target_region_id'].fillna(0).astype(int)

/var/folders/qr/zj6021nd67q4r28tdnk1qnw00000gn/T/ipykernel_86984/2483032313.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  target_region['target_country_id'] = target_region['target_country_id'].fillna(0).astype(int)
/var/folders/qr/zj6021nd67q4r28tdnk1qnw00000gn/T/ipykernel_86984/2483032313.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  target_region['target_region_id'] = target_region['target_region_id'].fillna(0).astype(int)

# Matching location data

In [10]:
target_matched = pd.merge(target_region, country_codes, left_on='target_country_id',right_on='country-code', how='left')
target_matched = pd.merge(target_matched, loc_region_codes, left_on='target_region_id', right_on='local_region_id', how='left')
target_matched = target_matched[['deal_id', 'target_country_id', 'target_region_id', 'region', 'country', 'local_region_name']]
target_matched.columns=['deal_id', 'target_country_id', 'target_region_id', 'target_region', 'target_country', 'target_local_region']

## Imputing missing values

In [11]:
# target_matched.target_region.value_counts()

In [12]:
# target_matched['target_region']=target_matched.target_region.fillna('Western Europe')

In [13]:
# target_matched.target_country.value_counts()

In [14]:
# target_matched['target_country']=target_matched.target_country.fillna('Germany')

In [15]:
# target_matched.target_local_region.value_counts()

In [16]:
# target_matched.head(30)

In [17]:
# import random
# import numpy as np
# local_regions = ['Bavaria', 'North Rhine-Westphalia', 'Baden-WÃ¼rttemberg', 'Hesse', 'Lower Saxony']
# target_matched['rand_local_region'] = np.resize(local_regions, len(target_matched))
# target_matched['target_local_region'] = target_matched.target_local_region.fillna(target_matched.rand_local_region)
# target_matched.drop(['rand_local_region'], axis=1, inplace=True)
# target_matched.head(30)

## OHE region

In [18]:
from sklearn.preprocessing import OneHotEncoder

ohe = OneHotEncoder(sparse = False)

ohe.fit(target_matched[['target_region']])

target_encoded = ohe.transform(target_matched[['target_region']])

encoded_df = target_matched.copy()

encoded_df['target_Eastern_Europe'], encoded_df['target_Northern_Africa'], encoded_df['target_Northern_America'], encoded_df['target_Northern_Europe'], encoded_df['target_Southern_Europe'], encoded_df['target_Western_Europe'], encoded_df['NaN_region'] = target_encoded.T

## OHE country

In [19]:
ohe = OneHotEncoder(sparse = False)

ohe.fit(target_matched[['target_country']])

target_country_encoded = ohe.transform(target_matched[['target_country']])

encoded_df['target_Austria'], encoded_df['target_Belgium'], encoded_df['target_Czechia'], encoded_df['target_Egypt'], encoded_df['target_Germany'], encoded_df['target_Italy'], encoded_df['target_Netherlands'],encoded_df['target_Norway'],encoded_df['target_Poland'],encoded_df['target_Portugal'],encoded_df['target_Romania'],encoded_df['target_Slovakia'],encoded_df['target_Spain'],encoded_df['target_Switzerland'],encoded_df['target_United_States_of_America'],encoded_df['NaN_country']= target_country_encoded.T

## OHE local region

In [20]:
ohe = OneHotEncoder(sparse = False)

ohe.fit(target_matched[['target_local_region']])

target_state_encoded = ohe.transform(target_matched[['target_local_region']])

encoded_df['target_Baden-WÃ¼rttemberg'], encoded_df['target_Bavaria'], encoded_df['target_Berlin'], encoded_df['target_Brandenburg'], encoded_df['target_Bremen'], encoded_df['target_Hamburg'],encoded_df['target_Hesse'],encoded_df['target_Lower_Saxony'],encoded_df['target_Mecklenburg-Vorpommern'],encoded_df['target_North_Rhine-Westphalia'],encoded_df['target_Rhineland-Palatinate'],encoded_df['target_Saarland'],encoded_df['target_Saxony'],encoded_df['target_Saxony-Anhalt'],encoded_df['target_Schleswig-Holstein'],encoded_df['target_Thuringia'],encoded_df['NaN_state'] = target_state_encoded.T

encoded_df = encoded_df.drop(['target_country_id', 'target_region_id', 'target_region', 'target_country', 'target_local_region', 'NaN_country', 'NaN_region', 'NaN_state'], axis=1)

encoded_df = encoded_df.groupby('deal_id').max().reset_index()
encoded_df

,deal_id,target_Eastern_Europe,target_Northern_Africa,target_Northern_America,target_Northern_Europe,target_Southern_Europe,target_Western_Europe,target_Austria,target_Belgium,target_Czechia,...,target_Hesse,target_Lower_Saxony,target_Mecklenburg-Vorpommern,target_North_Rhine-Westphalia,target_Rhineland-Palatinate,target_Saarland,target_Saxony,target_Saxony-Anhalt,target_Schleswig-Holstein,target_Thuringia
0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,4,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,5,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20237,29693,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
20238,29694,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
20239,29695,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
20240,29696,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
20241,29697,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0

# Merge all data and drop columns

In [21]:
merged_data=merged_data.drop(['company_category_id','company_state_id','fees_rate','inroad','exit_oriented_y','management_takeover_y','seriousness','agnostic_y','margin','created_at','updated_at','company_inroad_id','company_id','max_revenue','min_revenue','max_ebitda','min_ebitda','max_equity','min_equity','searchmandate','invest_profile_id'], axis=1)

final_df = pd.merge(merged_data, encoded_df, on='deal_id', how='left')

final_df_no_names = final_df.drop(['investor_name', 'name'],axis=1)

final_df_no_names = final_df_no_names.fillna(0)

In [23]:
final_df_no_names

,deal_id,result,investor_id,is_lost,target_revenue,target_ebitda,target_ebit,DISTRESSED_x,MAJORITY_x,MINORITY_x,...,target_Hesse,target_Lower_Saxony,target_Mecklenburg-Vorpommern,target_North_Rhine-Westphalia,target_Rhineland-Palatinate,target_Saarland,target_Saxony,target_Saxony-Anhalt,target_Schleswig-Holstein,target_Thuringia
0,3,0,1,0,-0.670000,-1.344,-1.400000,0,1,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,6,0,7,0,4.745455,4.080,4.250000,0,1,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,7,0,7,0,-0.209091,0.800,0.833333,0,1,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,8,0,7,1,4.954545,3.360,2.250000,0,1,0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
4,9,1,7,1,-0.118182,0.240,0.250000,0,1,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16994,29692,1,9992,0,-0.200000,-0.560,-0.591667,0,1,0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
16995,29693,0,9992,0,0.200000,-0.480,-0.500000,0,1,0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16996,29695,0,9992,1,-0.527273,-0.520,-0.541667,0,1,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16997,29696,0,9992,0,-0.163636,-0.320,-0.333333,0,1,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16998,29697,0,9992,0,-0.090909,-0.488,-0.516667,0,1,0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0