<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Cleaning-dataframes" data-toc-modified-id="Cleaning-dataframes-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Cleaning dataframes</a></span><ul class="toc-item"><li><span><a href="#Investors-regions-and-regions-of-interest" data-toc-modified-id="Investors-regions-and-regions-of-interest-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>Investors regions and regions of interest</a></span></li><li><span><a href="#Deals-and-targets" data-toc-modified-id="Deals-and-targets-1.2"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>Deals and targets</a></span></li><li><span><a href="#Investors-sectors-of-interest" data-toc-modified-id="Investors-sectors-of-interest-1.3"><span class="toc-item-num">1.3&nbsp;&nbsp;</span>Investors sectors of interest</a></span></li><li><span><a href="#Investor-profiles" data-toc-modified-id="Investor-profiles-1.4"><span class="toc-item-num">1.4&nbsp;&nbsp;</span>Investor profiles</a></span></li></ul></li><li><span><a href="#Merging" data-toc-modified-id="Merging-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Merging</a></span></li></ul></div>

Export intermediate and final dataframes

In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import pandas as pd
import numpy as np

In [3]:
file_path1= '/Users/sophie/code/DealMatch/DealMatch/raw_data/encoded_investors_regions.xlsx'
file_path2= '/Users/sophie/code/DealMatch/DealMatch/raw_data/deals_final_2.xlsx'
file_path3= '/Users/sophie/code/DealMatch/DealMatch/raw_data/sectors_encoding_no_exclude_clean.xlsx'
file_path4= '/Users/sophie/code/DealMatch/DealMatch/raw_data/invest_profile_transaction_no_exclude_final.xlsx'

In [4]:
investors_regions_df = pd.read_excel(file_path1)
investors_regions_df = investors_regions_df.drop(['Unnamed: 0'], axis=1)
investors_regions_df.head()

,id,name,company_category_id,company_state_id,fees_rate,inroad,exit_oriented,management_takeover,seriousness,agnostic,...,investment_Northern_Europe,investment_Polynesia,investment_South_America,investment_South-eastern_Asia,investment_Southern_Africa,investment_Southern_Asia,investment_Southern_Europe,investment_Western_Africa,investment_Western_Asia,investment_Western_Europe
0,1,Greencoat Capital,1,0,0.02,0.0,1.0,0.0,2.0,0.0,...,1,0,0,0,0,0,1,0,0,1
1,5,Daniel Vogel,1,0,0.02,4.0,1.0,0.0,2.0,0.0,...,0,0,0,0,0,0,0,0,0,1
2,7,AL Capital Holding GmbH & Co. KG,1,0,0.02,0.0,1.0,0.0,2.0,1.0,...,0,0,0,0,0,0,0,0,0,1
3,28,Piccard Capital Partner,1,0,0.02,0.0,1.0,0.0,2.0,0.0,...,1,0,0,0,0,0,1,0,1,1
4,30,Quandriga GmbH,1,0,NaN,0.0,1.0,0.0,2.0,0.0,...,0,0,0,0,0,0,0,0,0,1

In [5]:
deals_df = pd.read_excel(file_path2)
deals_df = deals_df.drop(['Unnamed: 0'], axis=1)
deals_df.head()

,deal_id,result,investor_id,is_lost,target_revenue,target_ebitda,target_ebit,DISTRESSED,MAJORITY,MINORITY,...,Pharmaceuticals,Professional Services (B2B),Real Estate,Retailing,Semiconductors & Semiconductor Equipment,Software & Services,Telecommunication Hardware,Telecommunication Services,Transportation,Utilities
0,3,0,1,0,-0.670000,-1.344,-1.400000,0,1,0,...,0,0,0,0,0,0,0,0,0,0
1,6,0,7,0,4.745455,4.080,4.250000,0,1,0,...,0,0,0,0,0,0,0,0,0,0
2,7,0,7,0,-0.209091,0.800,0.833333,0,1,0,...,0,0,0,0,0,0,0,0,0,0
3,8,0,7,1,4.954545,3.360,2.250000,0,1,0,...,0,1,0,0,0,0,0,0,1,0
4,9,1,7,1,-0.118182,0.240,0.250000,0,1,0,...,0,0,0,0,0,0,0,0,0,0

In [6]:
sectors_df = pd.read_excel(file_path3)
sectors_df = sectors_df.drop(['Unnamed: 0'], axis=1)
sectors_df.head()

,investor_id,name,Agriculture,Automotive,Biotechnology & Life Sciences,Chemicals,Computer Hardware & Equipment,Construction,Consumer Goods & Apparel,Defense,...,Professional Services (B2B),Real Estate,Retailing,Semiconductors & Semiconductor Equipment,Software & Services,Telecommunication Hardware,Telecommunication Services,Transportation,Utilities,sector_count
0,1,Greencoat Capital,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,3
1,5,Daniel Vogel,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2
2,6,Richmond View Ventures GmbH,0,0,0,0,0,0,1,0,...,0,0,0,0,1,0,0,0,0,3
3,28,Piccard Capital Partner,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,1
4,30,Quandriga GmbH,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,1

In [7]:
profiles_df = pd.read_excel(file_path4)
profiles_df = profiles_df.drop(['Unnamed: 0'], axis=1)
profiles_df.head()

,investor_id,exit_oriented,management_takeover,agnostic,no_fee,pays_1,pays_2,pays_3,fee_sharing_10,fee_sharing_25,...,DISTRESSED,GROWTH,INSOLVENCY,REAL_ESTATE,SEED,SUCCESSION,FULL,MAJORITY,MINORITY,no_stake_info
0,1,1,0,0,0,0,1,0,0,0,...,0,1,0,0,0,0,0,0,0,1
1,5,1,0,0,0,0,1,0,0,0,...,0,0,0,0,0,1,0,1,0,0
2,6,1,0,0,0,0,1,0,0,0,...,0,0,0,0,1,0,0,0,1,0
3,7,1,0,1,0,0,1,0,0,0,...,0,0,0,0,0,1,0,1,0,0
4,28,1,0,0,0,0,1,0,0,0,...,0,0,0,1,0,1,0,1,0,0

In [8]:
investors_regions_df.columns = ['investor_id', 'name', 'company_category_id', 'company_state_id', 'fees_rate',
       'inroad', 'exit_oriented', 'management_takeover', 'seriousness',
       'agnostic', 'margin', 'created_at', 'updated_at', 'company_inroad_id',
       'company_id', 'max_revenue', 'min_revenue', 'max_ebitda', 'min_ebitda',
       'max_equity', 'min_equity', 'searchmandate', 'invest_profile_id',
       'investor_Australia_and_New_Zealand', 'investor_Eastern_Africa',
       'investor_Eastern_Asia', 'investor_Eastern_Europe',
       'investor_Northern_Africa', 'investor_Northern America',
       'investor_Northern_Europe', 'investor_South_America',
       'investor_South_Eastern_Asia', 'investor_Southern_Africa',
       'investor_Southern_Asia', 'investor_Southern_Europe',
       'investor_Western_Africa', 'investor_Western Asia', 'investor_Western_Europe',
       'investment_Australia_and_New_Zealand', 'investment_Caribbean',
       'investment_Central_America', 'investment_Central_Asia',
       'investment_Eastern_Africa', 'investment_Eastern_Asia',
       'investment_Eastern_Europe',
       'investment_Latin_America_and_the_Caribbean', 'investment_Melanesia',
       'investment_Micronesia', 'investment_Middle_Africa',
       'investment_Northern_Africa', 'investment_Northern_America',
       'investment_Northern_Europe', 'investment_Polynesia',
       'investment_South_America', 'investment_South-eastern_Asia',
       'investment_Southern_Africa', 'investment_Southern_Asia',
       'investment_Southern_Europe', 'investment_Western_Africa',
       'investment_Western_Asia', 'investment_Western_Europe']

# Cleaning dataframes

## Investors regions and regions of interest

In [9]:
investors_regions_df.columns

Index(['investor_id', 'name', 'company_category_id', 'company_state_id',
       'fees_rate', 'inroad', 'exit_oriented', 'management_takeover',
       'seriousness', 'agnostic', 'margin', 'created_at', 'updated_at',
       'company_inroad_id', 'company_id', 'max_revenue', 'min_revenue',
       'max_ebitda', 'min_ebitda', 'max_equity', 'min_equity', 'searchmandate',
       'invest_profile_id', 'investor_Australia_and_New_Zealand',
       'investor_Eastern_Africa', 'investor_Eastern_Asia',
       'investor_Eastern_Europe', 'investor_Northern_Africa',
       'investor_Northern America', 'investor_Northern_Europe',
       'investor_South_America', 'investor_South_Eastern_Asia',
       'investor_Southern_Africa', 'investor_Southern_Asia',
       'investor_Southern_Europe', 'investor_Western_Africa',
       'investor_Western Asia', 'investor_Western_Europe',
       'investment_Australia_and_New_Zealand', 'investment_Caribbean',
       'investment_Central_America', 'investment_Central_Asia',
       'investment_Eastern_Africa', 'investment_Eastern_Asia',
       'investment_Eastern_Europe',
       'investment_Latin_America_and_the_Caribbean', 'investment_Melanesia',
       'investment_Micronesia', 'investment_Middle_Africa',
       'investment_Northern_Africa', 'investment_Northern_America',
       'investment_Northern_Europe', 'investment_Polynesia',
       'investment_South_America', 'investment_South-eastern_Asia',
       'investment_Southern_Africa', 'investment_Southern_Asia',
       'investment_Southern_Europe', 'investment_Western_Africa',
       'investment_Western_Asia', 'investment_Western_Europe'],
      dtype='object')

## Deals and targets

In [10]:
deals_df.columns

Index(['deal_id', 'result', 'investor_id', 'is_lost', 'target_revenue',
       'target_ebitda', 'target_ebit', 'DISTRESSED', 'MAJORITY', 'MINORITY',
       'OTHER', 'VC', 'NOT_SPECIFIED', 'NO_CAPACITY', 'NO_MA_PLANNED',
       'NO_REGION_FIT', 'NO_RESPONSE', 'NO_STRATEGIC_FIT', 'TOO_EXPENSIVE',
       'TOO_SMALL', 'Agriculture', 'Automotive',
       'Biotechnology & Life Sciences', 'Chemicals',
       'Computer Hardware & Equipment', 'Construction',
       'Consumer Goods & Apparel', 'Defense', 'Electronics', 'Energy',
       'Financial Services', 'Food & Beverages', 'Food & Staples Retailing',
       'Health Care Equipment & Services', 'IT services',
       'Industrial automation', 'Industrial products and services',
       'Insurance', 'Internet/ecommerce', 'Leisure & consumer services',
       'Manufacturing (other)', 'Media', 'Mining', 'Pharmaceuticals',
       'Professional Services (B2B)', 'Real Estate', 'Retailing',
       'Semiconductors & Semiconductor Equipment', 'Software & Services',
       'Telecommunication Hardware', 'Telecommunication Services',
       'Transportation', 'Utilities'],
      dtype='object')

In [11]:
sectors1 = ['Agriculture', 'Automotive',
       'Biotechnology & Life Sciences', 'Chemicals',
       'Computer Hardware & Equipment', 'Construction',
       'Consumer Goods & Apparel', 'Defense', 'Electronics', 'Energy',
       'Financial Services', 'Food & Beverages', 'Food & Staples Retailing',
       'Health Care Equipment & Services', 'IT services',
       'Industrial automation', 'Industrial products and services',
       'Insurance', 'Internet/ecommerce', 'Leisure & consumer services',
       'Manufacturing (other)', 'Media', 'Mining', 'Pharmaceuticals',
       'Professional Services (B2B)', 'Real Estate', 'Retailing',
       'Semiconductors & Semiconductor Equipment', 'Software & Services',
       'Telecommunication Hardware', 'Telecommunication Services',
       'Transportation', 'Utilities']

sectors2 = [x.replace(' ', '_').replace('&', 'and').replace('/', '_').replace('(','')
            .replace(')', '').lower() for x in sectors1]

In [12]:
deals_df.columns = ['deal_id', 'result', 'investor_id', 'is_lost', 'target_revenue',
                                'target_ebitda', 'target_ebit', 'DISTRESSED', 'MAJORITY', 'MINORITY',
                                'OTHER', 'VC', 'NOT_SPECIFIED', 'NO_CAPACITY', 'NO_MA_PLANNED',
                                'NO_REGION_FIT', 'NO_RESPONSE', 'NO_STRATEGIC_FIT', 'TOO_EXPENSIVE',
                                'TOO_SMALL'] + [f'target_{x}' for x in sectors2]

In [13]:
deals_df.columns

Index(['deal_id', 'result', 'investor_id', 'is_lost', 'target_revenue',
       'target_ebitda', 'target_ebit', 'DISTRESSED', 'MAJORITY', 'MINORITY',
       'OTHER', 'VC', 'NOT_SPECIFIED', 'NO_CAPACITY', 'NO_MA_PLANNED',
       'NO_REGION_FIT', 'NO_RESPONSE', 'NO_STRATEGIC_FIT', 'TOO_EXPENSIVE',
       'TOO_SMALL', 'target_agriculture', 'target_automotive',
       'target_biotechnology_and_life_sciences', 'target_chemicals',
       'target_computer_hardware_and_equipment', 'target_construction',
       'target_consumer_goods_and_apparel', 'target_defense',
       'target_electronics', 'target_energy', 'target_financial_services',
       'target_food_and_beverages', 'target_food_and_staples_retailing',
       'target_health_care_equipment_and_services', 'target_it_services',
       'target_industrial_automation',
       'target_industrial_products_and_services', 'target_insurance',
       'target_internet_ecommerce', 'target_leisure_and_consumer_services',
       'target_manufacturing_other', 'target_media', 'target_mining',
       'target_pharmaceuticals', 'target_professional_services_b2b',
       'target_real_estate', 'target_retailing',
       'target_semiconductors_and_semiconductor_equipment',
       'target_software_and_services', 'target_telecommunication_hardware',
       'target_telecommunication_services', 'target_transportation',
       'target_utilities'],
      dtype='object')

In [14]:
deals_df.head()

,deal_id,result,investor_id,is_lost,target_revenue,target_ebitda,target_ebit,DISTRESSED,MAJORITY,MINORITY,...,target_pharmaceuticals,target_professional_services_b2b,target_real_estate,target_retailing,target_semiconductors_and_semiconductor_equipment,target_software_and_services,target_telecommunication_hardware,target_telecommunication_services,target_transportation,target_utilities
0,3,0,1,0,-0.670000,-1.344,-1.400000,0,1,0,...,0,0,0,0,0,0,0,0,0,0
1,6,0,7,0,4.745455,4.080,4.250000,0,1,0,...,0,0,0,0,0,0,0,0,0,0
2,7,0,7,0,-0.209091,0.800,0.833333,0,1,0,...,0,0,0,0,0,0,0,0,0,0
3,8,0,7,1,4.954545,3.360,2.250000,0,1,0,...,0,1,0,0,0,0,0,0,1,0
4,9,1,7,1,-0.118182,0.240,0.250000,0,1,0,...,0,0,0,0,0,0,0,0,0,0

## Investors sectors of interest

In [15]:
sectors_df.columns

Index(['investor_id', 'name', 'Agriculture', 'Automotive',
       'Biotechnology & Life Sciences', 'Chemicals',
       'Computer Hardware & Equipment', 'Construction',
       'Consumer Goods & Apparel', 'Defense', 'Electronics', 'Energy',
       'Financial Services', 'Food & Beverages', 'Food & Staples Retailing',
       'Government', 'Health Care Equipment & Services', 'IT services',
       'Industrial automation', 'Industrial products and services',
       'Insurance', 'Internet/ecommerce', 'Leisure & consumer services',
       'Manufacturing (other)', 'Media', 'Mining', 'Pharmaceuticals',
       'Professional Services (B2B)', 'Real Estate', 'Retailing',
       'Semiconductors & Semiconductor Equipment', 'Software & Services',
       'Telecommunication Hardware', 'Telecommunication Services',
       'Transportation', 'Utilities', 'sector_count'],
      dtype='object')

In [16]:
sectors3 = ['Agriculture', 'Automotive', 'Biotechnology & Life Sciences', 'Chemicals',
            'Computer Hardware & Equipment', 'Construction', 'Consumer Goods & Apparel', 
            'Defense', 'Electronics', 'Energy', 'Financial Services', 'Food & Beverages', 
            'Food & Staples Retailing', 'Government', 'Health Care Equipment & Services', 
            'IT services', 'Industrial automation', 'Industrial products and services',
            'Insurance', 'Internet/ecommerce', 'Leisure & consumer services',
            'Manufacturing (other)', 'Media', 'Mining', 'Pharmaceuticals',
            'Professional Services (B2B)', 'Real Estate', 'Retailing',
            'Semiconductors & Semiconductor Equipment', 'Software & Services',
            'Telecommunication Hardware', 'Telecommunication Services','Transportation', 
            'Utilities']

sectors4 = [x.replace(' ', '_').replace('&', 'and').replace('/', '_').replace('(','')
            .replace(')', '').lower() for x in sectors3]

len(sectors4)

34

In [17]:
sectors4 =  ['name'] + sectors4 + ['sector_count']

In [18]:
sectors4 = ['investor_id'] + [f'investor_{x}' for x in sectors4]

In [19]:
sectors4

['investor_id',
 'investor_name',
 'investor_agriculture',
 'investor_automotive',
 'investor_biotechnology_and_life_sciences',
 'investor_chemicals',
 'investor_computer_hardware_and_equipment',
 'investor_construction',
 'investor_consumer_goods_and_apparel',
 'investor_defense',
 'investor_electronics',
 'investor_energy',
 'investor_financial_services',
 'investor_food_and_beverages',
 'investor_food_and_staples_retailing',
 'investor_government',
 'investor_health_care_equipment_and_services',
 'investor_it_services',
 'investor_industrial_automation',
 'investor_industrial_products_and_services',
 'investor_insurance',
 'investor_internet_ecommerce',
 'investor_leisure_and_consumer_services',
 'investor_manufacturing_other',
 'investor_media',
 'investor_mining',
 'investor_pharmaceuticals',
 'investor_professional_services_b2b',
 'investor_real_estate',
 'investor_retailing',
 'investor_semiconductors_and_semiconductor_equipment',
 'investor_software_and_services',
 'investor_telecommunication_hardware',
 'investor_telecommunication_services',
 'investor_transportation',
 'investor_utilities',
 'investor_sector_count']

In [20]:
sectors_df.columns = sectors4

In [21]:
sectors_df.head()

,investor_id,investor_name,investor_agriculture,investor_automotive,investor_biotechnology_and_life_sciences,investor_chemicals,investor_computer_hardware_and_equipment,investor_construction,investor_consumer_goods_and_apparel,investor_defense,...,investor_professional_services_b2b,investor_real_estate,investor_retailing,investor_semiconductors_and_semiconductor_equipment,investor_software_and_services,investor_telecommunication_hardware,investor_telecommunication_services,investor_transportation,investor_utilities,investor_sector_count
0,1,Greencoat Capital,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,3
1,5,Daniel Vogel,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2
2,6,Richmond View Ventures GmbH,0,0,0,0,0,0,1,0,...,0,0,0,0,1,0,0,0,0,3
3,28,Piccard Capital Partner,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,1
4,30,Quandriga GmbH,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,1

## Investor profiles

In [22]:
profiles_df.columns

Index(['investor_id', 'exit_oriented', 'management_takeover', 'agnostic',
       'no_fee', 'pays_1', 'pays_2', 'pays_3', 'fee_sharing_10',
       'fee_sharing_25', 'keine_marge', 'mind_10', 'mind_15', 'mind_20',
       'mind_5', 'undermanaged', 'CAPITAL_INCREASE', 'CARVE_OUT', 'DISTRESSED',
       'GROWTH', 'INSOLVENCY', 'REAL_ESTATE', 'SEED', 'SUCCESSION', 'FULL',
       'MAJORITY', 'MINORITY', 'no_stake_info'],
      dtype='object')

# Merging

In [23]:
deals_df

,deal_id,result,investor_id,is_lost,target_revenue,target_ebitda,target_ebit,DISTRESSED,MAJORITY,MINORITY,...,target_pharmaceuticals,target_professional_services_b2b,target_real_estate,target_retailing,target_semiconductors_and_semiconductor_equipment,target_software_and_services,target_telecommunication_hardware,target_telecommunication_services,target_transportation,target_utilities
0,3,0,1,0,-0.670000,-1.344,-1.400000,0,1,0,...,0,0,0,0,0,0,0,0,0,0
1,6,0,7,0,4.745455,4.080,4.250000,0,1,0,...,0,0,0,0,0,0,0,0,0,0
2,7,0,7,0,-0.209091,0.800,0.833333,0,1,0,...,0,0,0,0,0,0,0,0,0,0
3,8,0,7,1,4.954545,3.360,2.250000,0,1,0,...,0,1,0,0,0,0,0,0,1,0
4,9,1,7,1,-0.118182,0.240,0.250000,0,1,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16994,29692,1,9992,0,-0.200000,-0.560,-0.591667,0,1,0,...,0,0,0,0,0,0,0,0,1,0
16995,29693,0,9992,0,0.200000,-0.480,-0.500000,0,1,0,...,0,0,0,0,0,0,0,0,1,0
16996,29695,0,9992,1,-0.527273,-0.520,-0.541667,0,1,0,...,0,0,0,1,0,0,0,0,0,0
16997,29696,0,9992,0,-0.163636,-0.320,-0.333333,0,1,0,...,0,0,0,1,0,0,0,0,0,0
16998,29697,0,9992,0,-0.090909,-0.488,-0.516667,0,1,0,...,0,1,0,1,0,0,0,0,0,0

In [24]:
print(deals_df.investor_id.nunique())
print(profiles_df.investor_id.nunique())
print(investors_regions_df.investor_id.nunique())

1577
3186
2813

In [25]:
merged_df = pd.merge(deals_df, profiles_df, on='investor_id', how='left')

In [26]:
merged_df = pd.merge(merged_df, sectors_df, on='investor_id', how='left')

In [27]:
merged_df = pd.merge(merged_df, investors_regions_df, on='investor_id', how='left')

In [28]:
merged_df

,deal_id,result,investor_id,is_lost,target_revenue,target_ebitda,target_ebit,DISTRESSED_x,MAJORITY_x,MINORITY_x,...,investment_Northern_Europe,investment_Polynesia,investment_South_America,investment_South-eastern_Asia,investment_Southern_Africa,investment_Southern_Asia,investment_Southern_Europe,investment_Western_Africa,investment_Western_Asia,investment_Western_Europe
0,3,0,1,0,-0.670000,-1.344,-1.400000,0,1,0,...,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
1,6,0,7,0,4.745455,4.080,4.250000,0,1,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2,7,0,7,0,-0.209091,0.800,0.833333,0,1,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,8,0,7,1,4.954545,3.360,2.250000,0,1,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4,9,1,7,1,-0.118182,0.240,0.250000,0,1,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16994,29692,1,9992,0,-0.200000,-0.560,-0.591667,0,1,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
16995,29693,0,9992,0,0.200000,-0.480,-0.500000,0,1,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
16996,29695,0,9992,1,-0.527273,-0.520,-0.541667,0,1,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
16997,29696,0,9992,0,-0.163636,-0.320,-0.333333,0,1,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
16998,29697,0,9992,0,-0.090909,-0.488,-0.516667,0,1,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [29]:
[x for x in merged_df.columns]

['deal_id',
 'result',
 'investor_id',
 'is_lost',
 'target_revenue',
 'target_ebitda',
 'target_ebit',
 'DISTRESSED_x',
 'MAJORITY_x',
 'MINORITY_x',
 'OTHER',
 'VC',
 'NOT_SPECIFIED',
 'NO_CAPACITY',
 'NO_MA_PLANNED',
 'NO_REGION_FIT',
 'NO_RESPONSE',
 'NO_STRATEGIC_FIT',
 'TOO_EXPENSIVE',
 'TOO_SMALL',
 'target_agriculture',
 'target_automotive',
 'target_biotechnology_and_life_sciences',
 'target_chemicals',
 'target_computer_hardware_and_equipment',
 'target_construction',
 'target_consumer_goods_and_apparel',
 'target_defense',
 'target_electronics',
 'target_energy',
 'target_financial_services',
 'target_food_and_beverages',
 'target_food_and_staples_retailing',
 'target_health_care_equipment_and_services',
 'target_it_services',
 'target_industrial_automation',
 'target_industrial_products_and_services',
 'target_insurance',
 'target_internet_ecommerce',
 'target_leisure_and_consumer_services',
 'target_manufacturing_other',
 'target_media',
 'target_mining',
 'target_pharmaceuticals',
 'target_professional_services_b2b',
 'target_real_estate',
 'target_retailing',
 'target_semiconductors_and_semiconductor_equipment',
 'target_software_and_services',
 'target_telecommunication_hardware',
 'target_telecommunication_services',
 'target_transportation',
 'target_utilities',
 'exit_oriented_x',
 'management_takeover_x',
 'agnostic_x',
 'no_fee',
 'pays_1',
 'pays_2',
 'pays_3',
 'fee_sharing_10',
 'fee_sharing_25',
 'keine_marge',
 'mind_10',
 'mind_15',
 'mind_20',
 'mind_5',
 'undermanaged',
 'CAPITAL_INCREASE',
 'CARVE_OUT',
 'DISTRESSED_y',
 'GROWTH',
 'INSOLVENCY',
 'REAL_ESTATE',
 'SEED',
 'SUCCESSION',
 'FULL',
 'MAJORITY_y',
 'MINORITY_y',
 'no_stake_info',
 'investor_name',
 'investor_agriculture',
 'investor_automotive',
 'investor_biotechnology_and_life_sciences',
 'investor_chemicals',
 'investor_computer_hardware_and_equipment',
 'investor_construction',
 'investor_consumer_goods_and_apparel',
 'investor_defense',
 'investor_electronics',
 'investor_energy',
 'investor_financial_services',
 'investor_food_and_beverages',
 'investor_food_and_staples_retailing',
 'investor_government',
 'investor_health_care_equipment_and_services',
 'investor_it_services',
 'investor_industrial_automation',
 'investor_industrial_products_and_services',
 'investor_insurance',
 'investor_internet_ecommerce',
 'investor_leisure_and_consumer_services',
 'investor_manufacturing_other',
 'investor_media',
 'investor_mining',
 'investor_pharmaceuticals',
 'investor_professional_services_b2b',
 'investor_real_estate',
 'investor_retailing',
 'investor_semiconductors_and_semiconductor_equipment',
 'investor_software_and_services',
 'investor_telecommunication_hardware',
 'investor_telecommunication_services',
 'investor_transportation',
 'investor_utilities',
 'investor_sector_count',
 'name',
 'company_category_id',
 'company_state_id',
 'fees_rate',
 'inroad',
 'exit_oriented_y',
 'management_takeover_y',
 'seriousness',
 'agnostic_y',
 'margin',
 'created_at',
 'updated_at',
 'company_inroad_id',
 'company_id',
 'max_revenue',
 'min_revenue',
 'max_ebitda',
 'min_ebitda',
 'max_equity',
 'min_equity',
 'searchmandate',
 'invest_profile_id',
 'investor_Australia_and_New_Zealand',
 'investor_Eastern_Africa',
 'investor_Eastern_Asia',
 'investor_Eastern_Europe',
 'investor_Northern_Africa',
 'investor_Northern America',
 'investor_Northern_Europe',
 'investor_South_America',
 'investor_South_Eastern_Asia',
 'investor_Southern_Africa',
 'investor_Southern_Asia',
 'investor_Southern_Europe',
 'investor_Western_Africa',
 'investor_Western Asia',
 'investor_Western_Europe',
 'investment_Australia_and_New_Zealand',
 'investment_Caribbean',
 'investment_Central_America',
 'investment_Central_Asia',
 'investment_Eastern_Africa',
 'investment_Eastern_Asia',
 'investment_Eastern_Europe',
 'investment_Latin_America_and_the_Caribbean',
 'investment_Melanesia',
 'investment_Micronesia',
 'investment_Middle_Africa',
 'investment_Northern_Africa',
 'investment_Northern_America',
 'investment_Northern_Europe',
 'investment_Polynesia',
 'investment_South_America',
 'investment_South-eastern_Asia',
 'investment_Southern_Africa',
 'investment_Southern_Asia',
 'investment_Southern_Europe',
 'investment_Western_Africa',
 'investment_Western_Asia',
 'investment_Western_Europe']

In [31]:
merged_df = merged_df[['deal_id',
 'result',
 'investor_id','investor_name',
 'is_lost',
 'target_revenue',
 'target_ebitda',
 'target_ebit',
 'DISTRESSED_x',
 'MAJORITY_x',
 'MINORITY_x',
 'OTHER',
 'VC',
 'NOT_SPECIFIED',
 'NO_CAPACITY',
 'NO_MA_PLANNED',
 'NO_REGION_FIT',
 'NO_RESPONSE',
 'NO_STRATEGIC_FIT',
 'TOO_EXPENSIVE',
 'TOO_SMALL',
 'target_agriculture',
 'target_automotive',
 'target_biotechnology_and_life_sciences',
 'target_chemicals',
 'target_computer_hardware_and_equipment',
 'target_construction',
 'target_consumer_goods_and_apparel',
 'target_defense',
 'target_electronics',
 'target_energy',
 'target_financial_services',
 'target_food_and_beverages',
 'target_food_and_staples_retailing',
 'target_health_care_equipment_and_services',
 'target_it_services',
 'target_industrial_automation',
 'target_industrial_products_and_services',
 'target_insurance',
 'target_internet_ecommerce',
 'target_leisure_and_consumer_services',
 'target_manufacturing_other',
 'target_media',
 'target_mining',
 'target_pharmaceuticals',
 'target_professional_services_b2b',
 'target_real_estate',
 'target_retailing',
 'target_semiconductors_and_semiconductor_equipment',
 'target_software_and_services',
 'target_telecommunication_hardware',
 'target_telecommunication_services',
 'target_transportation',
 'target_utilities',
 'exit_oriented_x',
 'management_takeover_x',
 'agnostic_x',
 'no_fee',
 'pays_1',
 'pays_2',
 'pays_3',
 'fee_sharing_10',
 'fee_sharing_25',
 'keine_marge',
 'mind_10',
 'mind_15',
 'mind_20',
 'mind_5',
 'undermanaged',
 'CAPITAL_INCREASE',
 'CARVE_OUT',
 'DISTRESSED_y',
 'GROWTH',
 'INSOLVENCY',
 'REAL_ESTATE',
 'SEED',
 'SUCCESSION',
 'FULL',
 'MAJORITY_y',
 'MINORITY_y',
 'no_stake_info',
 'investor_agriculture',
 'investor_automotive',
 'investor_biotechnology_and_life_sciences',
 'investor_chemicals',
 'investor_computer_hardware_and_equipment',
 'investor_construction',
 'investor_consumer_goods_and_apparel',
 'investor_defense',
 'investor_electronics',
 'investor_energy',
 'investor_financial_services',
 'investor_food_and_beverages',
 'investor_food_and_staples_retailing',
 'investor_government',
 'investor_health_care_equipment_and_services',
 'investor_it_services',
 'investor_industrial_automation',
 'investor_industrial_products_and_services',
 'investor_insurance',
 'investor_internet_ecommerce',
 'investor_leisure_and_consumer_services',
 'investor_manufacturing_other',
 'investor_media',
 'investor_mining',
 'investor_pharmaceuticals',
 'investor_professional_services_b2b',
 'investor_real_estate',
 'investor_retailing',
 'investor_semiconductors_and_semiconductor_equipment',
 'investor_software_and_services',
 'investor_telecommunication_hardware',
 'investor_telecommunication_services',
 'investor_transportation',
 'investor_utilities',
 'investor_sector_count',
 'name',
 'company_category_id',
 'company_state_id',
 'fees_rate',
 'inroad',
 'exit_oriented_y',
 'management_takeover_y',
 'seriousness',
 'agnostic_y',
 'margin',
 'created_at',
 'updated_at',
 'company_inroad_id',
 'company_id',
 'max_revenue',
 'min_revenue',
 'max_ebitda',
 'min_ebitda',
 'max_equity',
 'min_equity',
 'searchmandate',
 'invest_profile_id',
 'investor_Australia_and_New_Zealand',
 'investor_Eastern_Africa',
 'investor_Eastern_Asia',
 'investor_Eastern_Europe',
 'investor_Northern_Africa',
 'investor_Northern America',
 'investor_Northern_Europe',
 'investor_South_America',
 'investor_South_Eastern_Asia',
 'investor_Southern_Africa',
 'investor_Southern_Asia',
 'investor_Southern_Europe',
 'investor_Western_Africa',
 'investor_Western Asia',
 'investor_Western_Europe',
 'investment_Australia_and_New_Zealand',
 'investment_Caribbean',
 'investment_Central_America',
 'investment_Central_Asia',
 'investment_Eastern_Africa',
 'investment_Eastern_Asia',
 'investment_Eastern_Europe',
 'investment_Latin_America_and_the_Caribbean',
 'investment_Melanesia',
 'investment_Micronesia',
 'investment_Middle_Africa',
 'investment_Northern_Africa',
 'investment_Northern_America',
 'investment_Northern_Europe',
 'investment_Polynesia',
 'investment_South_America',
 'investment_South-eastern_Asia',
 'investment_Southern_Africa',
 'investment_Southern_Asia',
 'investment_Southern_Europe',
 'investment_Western_Africa',
 'investment_Western_Asia',
 'investment_Western_Europe']]

In [33]:
[x for x in merged_df.columns]

['deal_id',
 'result',
 'investor_id',
 'investor_name',
 'is_lost',
 'target_revenue',
 'target_ebitda',
 'target_ebit',
 'DISTRESSED_x',
 'MAJORITY_x',
 'MINORITY_x',
 'OTHER',
 'VC',
 'NOT_SPECIFIED',
 'NO_CAPACITY',
 'NO_MA_PLANNED',
 'NO_REGION_FIT',
 'NO_RESPONSE',
 'NO_STRATEGIC_FIT',
 'TOO_EXPENSIVE',
 'TOO_SMALL',
 'target_agriculture',
 'target_automotive',
 'target_biotechnology_and_life_sciences',
 'target_chemicals',
 'target_computer_hardware_and_equipment',
 'target_construction',
 'target_consumer_goods_and_apparel',
 'target_defense',
 'target_electronics',
 'target_energy',
 'target_financial_services',
 'target_food_and_beverages',
 'target_food_and_staples_retailing',
 'target_health_care_equipment_and_services',
 'target_it_services',
 'target_industrial_automation',
 'target_industrial_products_and_services',
 'target_insurance',
 'target_internet_ecommerce',
 'target_leisure_and_consumer_services',
 'target_manufacturing_other',
 'target_media',
 'target_mining',
 'target_pharmaceuticals',
 'target_professional_services_b2b',
 'target_real_estate',
 'target_retailing',
 'target_semiconductors_and_semiconductor_equipment',
 'target_software_and_services',
 'target_telecommunication_hardware',
 'target_telecommunication_services',
 'target_transportation',
 'target_utilities',
 'exit_oriented_x',
 'management_takeover_x',
 'agnostic_x',
 'no_fee',
 'pays_1',
 'pays_2',
 'pays_3',
 'fee_sharing_10',
 'fee_sharing_25',
 'keine_marge',
 'mind_10',
 'mind_15',
 'mind_20',
 'mind_5',
 'undermanaged',
 'CAPITAL_INCREASE',
 'CARVE_OUT',
 'DISTRESSED_y',
 'GROWTH',
 'INSOLVENCY',
 'REAL_ESTATE',
 'SEED',
 'SUCCESSION',
 'FULL',
 'MAJORITY_y',
 'MINORITY_y',
 'no_stake_info',
 'investor_agriculture',
 'investor_automotive',
 'investor_biotechnology_and_life_sciences',
 'investor_chemicals',
 'investor_computer_hardware_and_equipment',
 'investor_construction',
 'investor_consumer_goods_and_apparel',
 'investor_defense',
 'investor_electronics',
 'investor_energy',
 'investor_financial_services',
 'investor_food_and_beverages',
 'investor_food_and_staples_retailing',
 'investor_government',
 'investor_health_care_equipment_and_services',
 'investor_it_services',
 'investor_industrial_automation',
 'investor_industrial_products_and_services',
 'investor_insurance',
 'investor_internet_ecommerce',
 'investor_leisure_and_consumer_services',
 'investor_manufacturing_other',
 'investor_media',
 'investor_mining',
 'investor_pharmaceuticals',
 'investor_professional_services_b2b',
 'investor_real_estate',
 'investor_retailing',
 'investor_semiconductors_and_semiconductor_equipment',
 'investor_software_and_services',
 'investor_telecommunication_hardware',
 'investor_telecommunication_services',
 'investor_transportation',
 'investor_utilities',
 'investor_sector_count',
 'name',
 'company_category_id',
 'company_state_id',
 'fees_rate',
 'inroad',
 'exit_oriented_y',
 'management_takeover_y',
 'seriousness',
 'agnostic_y',
 'margin',
 'created_at',
 'updated_at',
 'company_inroad_id',
 'company_id',
 'max_revenue',
 'min_revenue',
 'max_ebitda',
 'min_ebitda',
 'max_equity',
 'min_equity',
 'searchmandate',
 'invest_profile_id',
 'investor_Australia_and_New_Zealand',
 'investor_Eastern_Africa',
 'investor_Eastern_Asia',
 'investor_Eastern_Europe',
 'investor_Northern_Africa',
 'investor_Northern America',
 'investor_Northern_Europe',
 'investor_South_America',
 'investor_South_Eastern_Asia',
 'investor_Southern_Africa',
 'investor_Southern_Asia',
 'investor_Southern_Europe',
 'investor_Western_Africa',
 'investor_Western Asia',
 'investor_Western_Europe',
 'investment_Australia_and_New_Zealand',
 'investment_Caribbean',
 'investment_Central_America',
 'investment_Central_Asia',
 'investment_Eastern_Africa',
 'investment_Eastern_Asia',
 'investment_Eastern_Europe',
 'investment_Latin_America_and_the_Caribbean',
 'investment_Melanesia',
 'investment_Micronesia',
 'investment_Middle_Africa',
 'investment_Northern_Africa',
 'investment_Northern_America',
 'investment_Northern_Europe',
 'investment_Polynesia',
 'investment_South_America',
 'investment_South-eastern_Asia',
 'investment_Southern_Africa',
 'investment_Southern_Asia',
 'investment_Southern_Europe',
 'investment_Western_Africa',
 'investment_Western_Asia',
 'investment_Western_Europe']

In [36]:
merged_df.investor_name.fillna(merged_df.name, inplace=True)

/var/folders/qr/zj6021nd67q4r28tdnk1qnw00000gn/T/ipykernel_74195/2909130282.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  merged_df.investor_name.fillna(merged_df.name, inplace=True)

In [38]:
merged_df.to_excel('merged_df.xlsx')

In [39]:
merged_df

,deal_id,result,investor_id,investor_name,is_lost,target_revenue,target_ebitda,target_ebit,DISTRESSED_x,MAJORITY_x,...,investment_Northern_Europe,investment_Polynesia,investment_South_America,investment_South-eastern_Asia,investment_Southern_Africa,investment_Southern_Asia,investment_Southern_Europe,investment_Western_Africa,investment_Western_Asia,investment_Western_Europe
0,3,0,1,Greencoat Capital,0,-0.670000,-1.344,-1.400000,0,1,...,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
1,6,0,7,AL Capital Holding GmbH & Co. KG,0,4.745455,4.080,4.250000,0,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2,7,0,7,AL Capital Holding GmbH & Co. KG,0,-0.209091,0.800,0.833333,0,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,8,0,7,AL Capital Holding GmbH & Co. KG,1,4.954545,3.360,2.250000,0,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4,9,1,7,AL Capital Holding GmbH & Co. KG,1,-0.118182,0.240,0.250000,0,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16994,29692,1,9992,4elements holding GmbH,0,-0.200000,-0.560,-0.591667,0,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
16995,29693,0,9992,4elements holding GmbH,0,0.200000,-0.480,-0.500000,0,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
16996,29695,0,9992,4elements holding GmbH,1,-0.527273,-0.520,-0.541667,0,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
16997,29696,0,9992,4elements holding GmbH,0,-0.163636,-0.320,-0.333333,0,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
16998,29697,0,9992,4elements holding GmbH,0,-0.090909,-0.488,-0.516667,0,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [40]:
merged_df.duplicated().sum()

0